### ISSUE TITLE
isn't the Singleton missing the private constructor?

### ISSUE THREAD

**Issue by haemi** [burczyk/XcodeSwiftSnippets#15]
i.e.

```
    static let sharedInstance : <#SingletonClass#> = <#SingletonClass#>()

    private override init() {
    }
```

**Comment by burczyk** [comment]
It doesn't seem to work as expected:

![singleton](https://cloud.githubusercontent.com/assets/1155763/8860649/7e995450-3185-11e5-805e-22bf3eb38a64.png)

You can create instances even if you mark `init` as private and they have different addresses = they are different instances. Calling `sharedInstance` always returns the same object though.

**Comment by burczyk** [comment]
Well, it may be but it's still not 100% safe, see this:

![singleton](https://cloud.githubusercontent.com/assets/1155763/8860863/e6a37142-3186-11e5-896f-3a8d142c746e.png)

`private` keyword works only in different files, you can call `private` methods in this file anyway ([Apple docs](https://developer.apple.com/swift/blog/?id=5)). So it will work well for some cases but won't block anything if you have more than one class in one file.
