### ISSUE TITLE
Doesn't appear to be working via Alcatraz on Xcode 7.2.

### ISSUE THREAD

**Issue by JimVanG** [burczyk/XcodeSwiftSnippets#17]
I'm using Xcode 7.2, and I installed `XcodeSwiftSnippets` via Alcatraz, although I cannot get it to work. I've uninstalled the plugin, re-installed Alcatraz, restarted Xcode, restarted my Mac, cleared derived data, and forced a reload of the Alcatraz code bundle.

Am I doing something wrong or is there an issue with the plugins Alcatraz support?

**Comment by indrajitsinh** [comment]
does it support swift 2.1 ?

**Comment by burczyk** [comment]
@JimVanG `XcodeSwiftSnippets` is a plugin developed by @CodeEagle and you should probably ask this question here: https://github.com/CodeEagle/SwiftCodeSnippets :)

**Comment by CodeEagle** [comment]
@JimVanG Hi there, try to remove the file by 
`rm -rf /Users/lawlincoln/Library/Application Support/SelfStudio/conf`
then reinstall `XcodeSwiftSnippets` again.
Sorry for inconvenience
