### ISSUE TITLE
The documentation in README is not true for me

### ISSUE THREAD

**Issue by ayushgoel** [burczyk/XcodeSwiftSnippets#4]
https://github.com/burczyk/XcodeSwiftSnippets#how-to-import-all-code-snippets-to-xcode

When I `ls` the given directory, I am unable to find the `CodeSnippets` directory. Here is what I have:

```
> $ ls ~/Library/Developer/Xcode/UserData/
FontAndColorThemes/                       IDEPreferencesController.xcuserstate
IDEDocumentationWindow.xcuserstate        KeyBindings/
IDEOrganizerWindowController.xcuserstate  SearchScopes.xcsclist
```

Note: Xcode Version 6.2 (6C131e)

**Comment by burczyk** [comment]
@ayushgoel can you simply create `CodeSnippets` directory and put all files inside? Maybe it's created after first code snippet is added manually from Xcode. Try that and let me know if it works for you.

**Comment by ayushgoel** [comment]
Wow! That solves it.
In case you think this is good enough info to be added to the README, just comment here, I will create a pull request. :relaxed: 
Closing the issue till then.

**Comment by burczyk** [comment]
Sure, feel free to make one :)
