### ISSUE TITLE
swift-uitableviewdatasource.codesnippet

### ISSUE THREAD

**Issue by X140Yu** [burczyk/XcodeSwiftSnippets#9]
in function `tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath)` `as` should be `as!`

**Comment by burczyk** [comment]
Aren't you looking at some old code? It was updated 19 days ago.

**Comment by X140Yu** [comment]
I mean the code in plist folder hasn't been modified.

**Comment by burczyk** [comment]
Thanks, fixed.
